version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '${SUBGRAPH_HTTP_PORT}:8000'
      - '${SUBGRAPH_WS_PORT}:8001'
      - '${SUBGRAPH_PORT_3}:8020'
      - '${GRAPHQL_PORT}:8030'
      - '${SUBGRAPH_PORT_5}:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: ${RPC_NODE}
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '${IPFS_PORT}:5001'
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - '8545:8545'